### ISSUE TITLE
Significant effects view may be ambiguous

### ISSUE THREAD

**Issue by rdewijn** [tercen/ttest_app#3]
Significants effects view in the app may be ambiguous because it shows a heatmap with 3 separate values per cell.

Take a mean per cell between scaling and heatmap view.

**Comment by ginberg** [comment]
hi @rdewijn, not sure If I understand this correctly. To me it seams there is 1 value per cell (for every barcode in Factor1). Or should there be just a single value per Factor1 (e.g. "Control" or "Treatment")?

**Comment by rdewijn** [comment]
You're right. looks like I removed a factor from the view
